"""Golden vector tests for BCS serialization.

These tests assert that our Python BCS output matches the official IOTA
TypeScript SDK (@iota/iota-sdk) byte-for-byte. The expected values in
golden_vectors.json were generated by generate.cjs using the TS SDK.

This is the highest-value test file in the project -- if the hand-rolled
BCS serialization diverges from the official SDK, transactions will be
rejected by IOTA nodes.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from pyiota.bcs import BcsWriter
from pyiota.bcs_types import (
    ADDRESS_LENGTH,
    Argument,
    ArgumentKind,
    BcsObjectRef,
    CallArg,
    CallArgKind,
    Command,
    CommandKind,
    GasPayment,
    ObjectArgKind,
    ProgrammableMoveCall,
    ProgrammableTransaction,
    SharedObjectRef,
    TransactionData,
    _serialize_type_tag,
    serialize_pure_address,
    serialize_pure_bool,
    serialize_pure_string,
    serialize_pure_u8,
    serialize_pure_u16,
    serialize_pure_u32,
    serialize_pure_u64,
    serialize_pure_u128,
    serialize_pure_u256,
)


@pytest.fixture(scope="module")
def vectors() -> dict[str, str]:
    """Load golden vectors generated by the official IOTA TypeScript SDK."""
    path = Path(__file__).parent / "golden_vectors.json"
    with open(path) as f:
        return json.load(f)


# -- Helpers --


def _addr_bytes(hex_pattern: str) -> bytes:
    """Convert a 0x-prefixed hex address to 32 bytes, zero-padded."""
    return bytes.fromhex(hex_pattern.removeprefix("0x").zfill(ADDRESS_LENGTH * 2))


def _digest_bytes() -> bytes:
    """The known test digest: bytes 0x00..0x1f."""
    return bytes(range(32))


def _digest_base58(vectors: dict[str, str]) -> str:
    """The Base58-encoded form of the test digest, from the TS SDK."""
    return vectors["object_digest_base58_input"]


# ============================================================
# 1. Pure value serialization (raw BCS primitives)
# ============================================================


class TestPureValueVectors:
    """Raw BCS primitive encoding must match the TS SDK exactly."""

    def test_u8_zero(self, vectors):
        assert serialize_pure_u8(0).hex() == vectors["pure_u8_0"]

    def test_u8_max(self, vectors):
        assert serialize_pure_u8(255).hex() == vectors["pure_u8_255"]

    def test_u16(self, vectors):
        assert serialize_pure_u16(256).hex() == vectors["pure_u16_256"]

    def test_u32(self, vectors):
        assert serialize_pure_u32(1).hex() == vectors["pure_u32_1"]

    def test_u64_billion(self, vectors):
        assert serialize_pure_u64(1_000_000_000).hex() == vectors["pure_u64_1000000000"]

    def test_u64_max(self, vectors):
        assert serialize_pure_u64(2**64 - 1).hex() == vectors["pure_u64_max"]

    def test_u128_one(self, vectors):
        assert serialize_pure_u128(1).hex() == vectors["pure_u128_1"]

    def test_u128_max(self, vectors):
        assert serialize_pure_u128(2**128 - 1).hex() == vectors["pure_u128_max"]

    def test_u256_one(self, vectors):
        assert serialize_pure_u256(1).hex() == vectors["pure_u256_1"]

    def test_bool_true(self, vectors):
        assert serialize_pure_bool(True).hex() == vectors["pure_bool_true"]

    def test_bool_false(self, vectors):
        assert serialize_pure_bool(False).hex() == vectors["pure_bool_false"]

    def test_string_hello(self, vectors):
        assert serialize_pure_string("hello").hex() == vectors["pure_string_hello"]

    def test_string_empty(self, vectors):
        assert serialize_pure_string("").hex() == vectors["pure_string_empty"]

    def test_address(self, vectors):
        addr = "0x" + "ab" * 32
        assert serialize_pure_address(addr).hex() == vectors["pure_address"]

    def test_address_short_zero_padded(self, vectors):
        """A short address like 0x1 must be left-padded to 32 bytes."""
        assert serialize_pure_address("0x1").hex() == vectors["pure_address_short"]


# ============================================================
# 2. ObjectDigest (length-prefixed, not fixed bytes)
# ============================================================


class TestObjectDigestVectors:
    def test_object_digest_length_prefixed(self, vectors):
        """ObjectDigest is BCS bytes (ULEB128 length prefix + 32 raw bytes)."""
        digest = _digest_bytes()
        w = BcsWriter()
        # ObjectDigest wraps Digest which serializes as Vec<u8>
        w.write_bytes(digest)
        assert w.finish().hex() == vectors["object_digest"]


# ============================================================
# 3. IotaObjectRef (BcsObjectRef in our code)
# ============================================================


class TestObjectRefVectors:
    def test_iota_object_ref(self, vectors):
        """object_id (32 fixed) + version (u64) + digest (length-prefixed)."""
        ref = BcsObjectRef(
            object_id=_addr_bytes("0x" + "a1" * 32),
            version=42,
            digest=_digest_bytes(),
        )
        assert ref.serialize().hex() == vectors["iota_object_ref"]


# ============================================================
# 4. SharedObjectRef
# ============================================================


class TestSharedObjectRefVectors:
    def test_shared_mutable(self, vectors):
        ref = SharedObjectRef(
            object_id=_addr_bytes("0x" + "b2" * 32),
            initial_shared_version=100,
            mutable=True,
        )
        assert ref.serialize().hex() == vectors["shared_object_ref"]

    def test_shared_immutable(self, vectors):
        ref = SharedObjectRef(
            object_id=_addr_bytes("0x" + "b2" * 32),
            initial_shared_version=100,
            mutable=False,
        )
        assert ref.serialize().hex() == vectors["shared_object_ref_immutable"]


# ============================================================
# 5. Argument variants
# ============================================================


class TestArgumentVectors:
    def test_gas_coin(self, vectors):
        arg = Argument(kind=ArgumentKind.GAS_COIN)
        assert arg.serialize().hex() == vectors["argument_gas_coin"]

    def test_input_0(self, vectors):
        arg = Argument(kind=ArgumentKind.INPUT, index=0)
        assert arg.serialize().hex() == vectors["argument_input_0"]

    def test_input_5(self, vectors):
        arg = Argument(kind=ArgumentKind.INPUT, index=5)
        assert arg.serialize().hex() == vectors["argument_input_5"]

    def test_result_0(self, vectors):
        arg = Argument(kind=ArgumentKind.RESULT, index=0)
        assert arg.serialize().hex() == vectors["argument_result_0"]

    def test_result_3(self, vectors):
        arg = Argument(kind=ArgumentKind.RESULT, index=3)
        assert arg.serialize().hex() == vectors["argument_result_3"]

    def test_nested_result(self, vectors):
        arg = Argument(kind=ArgumentKind.NESTED_RESULT, index=2, nested_index=1)
        assert arg.serialize().hex() == vectors["argument_nested_result"]


# ============================================================
# 6. CallArg variants
# ============================================================


class TestCallArgVectors:
    def test_pure_u64(self, vectors):
        """Pure CallArg: variant 0, then length-prefixed BCS value bytes."""
        pure_data = serialize_pure_u64(1_000_000_000)
        arg = CallArg(kind=CallArgKind.PURE, pure_data=pure_data)
        assert arg.serialize().hex() == vectors["call_arg_pure_u64"]

    def test_object_owned(self, vectors):
        obj_ref = BcsObjectRef(
            object_id=_addr_bytes("0x" + "a1" * 32),
            version=42,
            digest=_digest_bytes(),
        )
        arg = CallArg(
            kind=CallArgKind.OBJECT,
            object_kind=ObjectArgKind.IMM_OR_OWNED_OBJECT,
            object_ref=obj_ref,
        )
        assert arg.serialize().hex() == vectors["call_arg_object_owned"]

    def test_object_shared(self, vectors):
        shared_ref = SharedObjectRef(
            object_id=_addr_bytes("0x" + "b2" * 32),
            initial_shared_version=100,
            mutable=True,
        )
        arg = CallArg(
            kind=CallArgKind.OBJECT,
            object_kind=ObjectArgKind.SHARED_OBJECT,
            shared_ref=shared_ref,
        )
        assert arg.serialize().hex() == vectors["call_arg_object_shared"]

    def test_object_receiving(self, vectors):
        obj_ref = BcsObjectRef(
            object_id=_addr_bytes("0x" + "a1" * 32),
            version=42,
            digest=_digest_bytes(),
        )
        arg = CallArg(
            kind=CallArgKind.OBJECT,
            object_kind=ObjectArgKind.RECEIVING,
            object_ref=obj_ref,
        )
        assert arg.serialize().hex() == vectors["call_arg_object_receiving"]


# ============================================================
# 7. TypeTag serialization
# ============================================================


class TestTypeTagVectors:
    """TypeTag variant indices follow the IOTA BCS schema order, which
    differs from numeric order: bool=0, u8=1, u64=2, u128=3, address=4,
    signer=5, vector=6, struct=7, u16=8, u32=9, u256=10."""

    @pytest.mark.parametrize(
        "type_str,key",
        [
            ("bool", "type_tag_bool"),
            ("u8", "type_tag_u8"),
            ("u16", "type_tag_u16"),
            ("u32", "type_tag_u32"),
            ("u64", "type_tag_u64"),
            ("u128", "type_tag_u128"),
            ("u256", "type_tag_u256"),
            ("address", "type_tag_address"),
            ("signer", "type_tag_signer"),
        ],
    )
    def test_primitive_types(self, vectors, type_str, key):
        assert _serialize_type_tag(type_str).hex() == vectors[key]

    def test_vector_u8(self, vectors):
        assert _serialize_type_tag("vector<u8>").hex() == vectors["type_tag_vector_u8"]

    def test_struct_iota(self, vectors):
        """0x2::iota::IOTA -- a simple struct with no generics."""
        assert _serialize_type_tag("0x2::iota::IOTA").hex() == vectors["type_tag_struct_iota"]

    def test_struct_coin_with_generic(self, vectors):
        """0x2::coin::Coin<0x2::iota::IOTA> -- struct with one type parameter."""
        result = _serialize_type_tag("0x2::coin::Coin<0x2::iota::IOTA>")
        assert result.hex() == vectors["type_tag_struct_coin"]

    def test_vector_of_struct(self, vectors):
        """vector<0x2::coin::Coin<0x2::iota::IOTA>> -- nested generics."""
        result = _serialize_type_tag("vector<0x2::coin::Coin<0x2::iota::IOTA>>")
        assert result.hex() == vectors["type_tag_vector_coin"]

    def test_multi_generic(self, vectors):
        """0x1::pair::Pair<u64, address> -- struct with two type params."""
        result = _serialize_type_tag("0x1::pair::Pair<u64, address>")
        assert result.hex() == vectors["type_tag_multi_generic"]


# ============================================================
# 8. Command variants
# ============================================================


class TestCommandVectors:
    def test_split_coins(self, vectors):
        cmd = Command(
            kind=CommandKind.SPLIT_COINS,
            split_coin=Argument(kind=ArgumentKind.GAS_COIN),
            split_amounts=[Argument(kind=ArgumentKind.INPUT, index=0)],
        )
        assert cmd.serialize().hex() == vectors["command_split_coins"]

    def test_transfer_objects(self, vectors):
        cmd = Command(
            kind=CommandKind.TRANSFER_OBJECTS,
            transfer_objects=[Argument(kind=ArgumentKind.RESULT, index=0)],
            transfer_recipient=Argument(kind=ArgumentKind.INPUT, index=1),
        )
        assert cmd.serialize().hex() == vectors["command_transfer_objects"]

    def test_merge_coins(self, vectors):
        cmd = Command(
            kind=CommandKind.MERGE_COINS,
            merge_destination=Argument(kind=ArgumentKind.INPUT, index=0),
            merge_sources=[Argument(kind=ArgumentKind.INPUT, index=1)],
        )
        assert cmd.serialize().hex() == vectors["command_merge_coins"]

    def test_move_call(self, vectors):
        cmd = Command(
            kind=CommandKind.MOVE_CALL,
            move_call=ProgrammableMoveCall(
                package=_addr_bytes("0x2"),
                module="coin",
                function="split",
                type_arguments=["0x2::iota::IOTA"],
                arguments=[
                    Argument(kind=ArgumentKind.GAS_COIN),
                    Argument(kind=ArgumentKind.INPUT, index=0),
                ],
            ),
        )
        assert cmd.serialize().hex() == vectors["command_move_call"]


# ============================================================
# 9. ProgrammableTransaction
# ============================================================


class TestProgrammableTransactionVectors:
    def test_split_and_transfer(self, vectors):
        """A typical PTB: split 1 IOTA from gas, transfer to recipient."""
        ptb = ProgrammableTransaction(
            inputs=[
                # Input 0: pure u64 amount (1 IOTA in nanos)
                CallArg(kind=CallArgKind.PURE, pure_data=serialize_pure_u64(1_000_000_000)),
                # Input 1: pure address (recipient)
                CallArg(kind=CallArgKind.PURE, pure_data=serialize_pure_address("0x" + "dd" * 32)),
            ],
            commands=[
                # SplitCoins(GasCoin, [Input(0)])
                Command(
                    kind=CommandKind.SPLIT_COINS,
                    split_coin=Argument(kind=ArgumentKind.GAS_COIN),
                    split_amounts=[Argument(kind=ArgumentKind.INPUT, index=0)],
                ),
                # TransferObjects([Result(0)], Input(1))
                Command(
                    kind=CommandKind.TRANSFER_OBJECTS,
                    transfer_objects=[Argument(kind=ArgumentKind.RESULT, index=0)],
                    transfer_recipient=Argument(kind=ArgumentKind.INPUT, index=1),
                ),
            ],
        )
        assert ptb.serialize().hex() == vectors["programmable_transaction"]


# ============================================================
# 10. Full TransactionData
# ============================================================


def _build_test_tx_data(*, expiration_epoch: int | None = None) -> TransactionData:
    """Build the canonical test transaction used across golden vector tests."""
    sender = _addr_bytes("0x" + "cc" * 32)
    digest = _digest_bytes()

    ptb = ProgrammableTransaction(
        inputs=[
            CallArg(kind=CallArgKind.PURE, pure_data=serialize_pure_u64(1_000_000_000)),
            CallArg(kind=CallArgKind.PURE, pure_data=serialize_pure_address("0x" + "dd" * 32)),
        ],
        commands=[
            Command(
                kind=CommandKind.SPLIT_COINS,
                split_coin=Argument(kind=ArgumentKind.GAS_COIN),
                split_amounts=[Argument(kind=ArgumentKind.INPUT, index=0)],
            ),
            Command(
                kind=CommandKind.TRANSFER_OBJECTS,
                transfer_objects=[Argument(kind=ArgumentKind.RESULT, index=0)],
                transfer_recipient=Argument(kind=ArgumentKind.INPUT, index=1),
            ),
        ],
    )

    gas = GasPayment(
        payment=[
            BcsObjectRef(
                object_id=_addr_bytes("0x" + "ee" * 32),
                version=10,
                digest=digest,
            )
        ],
        owner=sender,
        price=1000,
        budget=50_000_000,
    )

    return TransactionData(
        kind=ptb,
        sender=sender,
        gas=gas,
        expiration_epoch=expiration_epoch,
    )


class TestTransactionDataVectors:
    def test_full_transaction_no_expiry(self, vectors):
        """Complete TransactionData V1 with no expiration."""
        tx = _build_test_tx_data()
        assert tx.serialize().hex() == vectors["transaction_data_full"]

    def test_full_transaction_with_expiry(self, vectors):
        """Complete TransactionData V1 with epoch expiration."""
        tx = _build_test_tx_data(expiration_epoch=100)
        assert tx.serialize().hex() == vectors["transaction_data_with_expiry"]


# ============================================================
# 11. Intent message
# ============================================================


class TestIntentMessageVectors:
    def test_intent_prefix(self, vectors):
        """Intent prefix for transaction signing is [0, 0, 0]."""
        from pyiota.crypto.signature import TRANSACTION_DATA_INTENT

        assert TRANSACTION_DATA_INTENT.hex() == vectors["intent_message_prefix"]

    def test_intent_message_construction(self, vectors):
        """Intent message = prefix + tx_data_bcs."""
        from pyiota.crypto.signature import make_intent_message

        tx = _build_test_tx_data()
        tx_bcs = tx.serialize()
        intent_msg = make_intent_message(tx_bcs)

        expected_prefix = bytes.fromhex(vectors["intent_message_prefix"])
        assert intent_msg[:3] == expected_prefix
        assert intent_msg[3:] == tx_bcs


# ============================================================
# 12. Ed25519 keypair and signature (deterministic seed)
# ============================================================


class TestSignatureVectors:
    """Verify our Ed25519 signing matches the TS SDK for a known keypair.

    Uses the deterministic seed 0x00..0x1f so both SDKs produce the
    same public key, address, and signature.
    """

    def test_public_key(self, vectors):
        from pyiota.crypto.ed25519 import Ed25519Keypair

        kp = Ed25519Keypair.from_secret_key(bytes(range(32)))
        assert kp.public_key.hex() == vectors["ed25519_public_key"]

    def test_address_derivation(self, vectors):
        from pyiota.crypto.ed25519 import Ed25519Keypair

        kp = Ed25519Keypair.from_secret_key(bytes(range(32)))
        assert kp.address == vectors["ed25519_address"]

    def test_intent_hash(self, vectors):
        """Blake2b-256(intent_prefix || tx_data_bcs) must match the TS SDK."""
        from pyiota.crypto.signature import hash_intent_message, make_intent_message

        tx = _build_test_tx_data()
        tx_bcs = tx.serialize()
        # Sanity: our tx_data_bcs matches the TS SDK's
        assert tx_bcs.hex() == vectors["tx_data_bcs"]

        intent_msg = make_intent_message(tx_bcs)
        intent_hash = hash_intent_message(intent_msg)
        assert intent_hash.hex() == vectors["intent_hash"]

    def test_raw_signature(self, vectors):
        """Ed25519 signature over the intent hash must match byte-for-byte."""
        from pyiota.crypto.ed25519 import Ed25519Keypair
        from pyiota.crypto.signature import hash_intent_message, make_intent_message

        kp = Ed25519Keypair.from_secret_key(bytes(range(32)))
        tx = _build_test_tx_data()
        intent_msg = make_intent_message(tx.serialize())
        intent_hash = hash_intent_message(intent_msg)

        sig = kp.sign(intent_hash)
        assert sig.hex() == vectors["ed25519_signature"]

    def test_serialized_signature(self, vectors):
        """Full serialized signature (flag || sig || pubkey, base64) must match."""
        from pyiota.crypto.ed25519 import Ed25519Keypair

        kp = Ed25519Keypair.from_secret_key(bytes(range(32)))
        tx = _build_test_tx_data()
        serialized = kp.sign_transaction(tx.serialize())
        assert serialized == vectors["serialized_signature_base64"]
